<?php

add_action( 'the_content', 'arrayImporter' );

function arrayImporter () {

    $default = array(
            'currency'      => '$',
            'ba'            => 'before',
            'currencyspace' => false,
            'separator'     => 'none',
            'decimalcomma'  => '',
            'decimals'	    => 'always',
            'rounding'      => 'noround',
            'loan'          => array(
                array(
                    'min'   => 100,
                    'max'   => 900,
                    'step'  => 100,
                ),
                array(
                    'min'   => 1000,
                    'max'   => 10000,
                    'step'  => 500,
                ),
                array(
                    'min'   => '',
                    'max'   => '',
                    'step'  => '',
                )
            ),
            'period'        => array(
                array(
                    'min'   => 7,
                    'max'   => 14,
                    'step'  => 7,
                    'term'  => 'D',
                ),
                array(
                    'min'   => 1,
                    'max'   => 11,
                    'step'  => 1,
                    'term'  => 'M',
                ),
                array(
                    'min'   => 1,
                    'max'   => 18,
                    'step'  => 1,
                    'term'  => 'Y',
                )
            ),
            'loaninitial'   => 10,
            'periodinitial' => 15,
            'loanhide'      => false,
            'termhide'      => false,
            'napr'          => false,
            'barchartenabled'=> false,
            'barchartorder'=> false,
            'formtitle'     => 'Loan Comparisons',
            'showfeatures'  => '',
            'feature1'      => 'Compare loans',
            'feature2'      => 'Sort results',
            'feature3'      => 'Apply online',
            'showfilters'   => '',
            'filterlabel'   => __('Filter for:', 'loan-comparison'),
            'filterlabel1'  => __('Under 18 loans', 'loan-comparison'),
            'filterlabel2'  => __('Zero fees', 'loan-comparison'),
            'filterlabel3'  => __('Early repayment', 'loan-comparison'),
            'filterlabel4'  => '',
            'filterlabel5'  => '',
            'filterdefault' => '',
            'showfilterdropdown'=> '',
            'showheader'    => '',
            'loanlabel'     => __('Loans From', 'loan-comparison'),
            'loanslabel'    => __('Min/Max Loan', 'loan-comparison'),
            'feeslabel'     => __('Admin Fee', 'loan-comparison'),
            'interestlabel' => __('Typical Interest', 'loan-comparison'),
            'interestamountlabel'=> __('Total Interest', 'loan-comparison'),
            'repaymentlabel'=> __('Repayments', 'loan-comparison'),
            'totallabel'    => __('Total Cost', 'loan-comparison'),
            'termlabel'     => __('Min/Max Term', 'loan-comparison'),
            'applylabel'    => __('Apply Now', 'loan-comparison'),
            'loancostlabel'    => __('Loan Cost', 'loan-comparison'),
            'otherinfolabel'    => __('Other Info', 'loan-comparison'),
            'ratinglabel'	=> __('Bank Rating', 'loan-comparison'),
            'banknamelabel'	=> __('Bank Name', 'loan-comparison'),
            'sponsoredlabel'=> __('Sponsored', 'loan-comparison'),
            'infolinklabel' => __('More Info', 'loan-comparison'),
            'infolinkanchor'=> __('Read More', 'loan-comparison'),
            'showmoreinfo'  => 'checked',
            'moreinfo'      => __('More Information', 'loan-comparison'),
            'info1label'    => __('Free Bananas', 'loan-comparison'),
            'info2label'    => __('Daily Newspapers', 'loan-comparison'),
            'info3label'    => __('Meet Penguins', 'loan-comparison'),
            'info4label'    => __('Eat More Fruit', 'loan-comparison'),
            'showchecks'    => '',
            'check1'        => 'Free Beer',
            'check2'        => 'Open All Day',
            'check3'        => 'Cuddly Toys',
            'check4'        => 'Aardvarks',
            'showexample'   => '',
            'examplelocation'   => 'grid',
            'logonofollow'  => '',
            'logoblank'     => 'checked',
            'buttonnofollow'=> '',
            'buttonblank'   => 'checked',
            'addterms'      => '',
            'loanslider'    => __('Amount:', 'loan-comparison'),
            'termslider'    => __('Term:', 'loan-comparison'),
            'numbertoshow'  => 10,
            'numbertoshowlabel'=> __('Show more results', 'loan-comparison'),
            'daylabel'      => __('Day', 'loan-comparison'),
            'monthlabel'    => __('Month', 'loan-comparison'),
            'yearlabel'     => __('Year', 'loan-comparison'),
            'dayslabel'      => __('Days', 'loan-comparison'),
            'monthslabel'    => __('Months', 'loan-comparison'),
            'yearslabel'     => __('Years', 'loan-comparison'),
            'showoffers'    => '',
            'offers'        => __('We have found [number] matches for you', 'loan-comparison'),
            'one-offer'     => __('We have found one match for you', 'loan-comparison'),
            'no-offers'     => __('There are no matches. Search again', 'loan-comparison'),
            'addfees'       => '',
            'whenfees'      => 'beforeinterest',
            'termseparator' => '-',
            'showrating'    => '',
            'maxrating'     => 5,

            'showsorting'   => false,
            'columnsorting' => false,
            'sortbylabel'   => __('Sort by:', 'loan-comparison'),
            'sortrating'    => __('Highest Rating', 'loan-comparison'),
            'sortinterest'  => __('Lowest Interest Rate', 'loan-comparison'),
            'sortloanamount'=> __('Smallest Loan Amount', 'loan-comparison'),
            'sortbankname'  => __('Bank Name', 'loan-comparison'),
            'sortfees'      => __('Lowest Fees', 'loan-comparison'),
            'sortrepayment' => __('Repayments', 'loan-comparison'),
            'sorttotal'     => __('Total to Pay', 'loan-comparison'),
            'sortterm'      => __('Terms', 'loan-comparison'),

            'sort_rating'    => 'checked',
            'sort_interest'  => 'checked',
            'sort_loanamount'=> 'checked',
            'sort_bankname'  => 'checked',
            'sort_fees'      => '',
            'sort_repayment' => 'checked',
            'sort_total'     => 'checked',
            'sort_term'      => '',

            'sortby'        => 'rating,interest,bankname,fees,term,repayment,total',
            'columnsort'	=> 'rating,interest,bankname,loanamount,interestamount,loan,fees,repayment,total,term,infolink,loancost,otherinfo',
            'showlimits'    => '',
            'minfee'        => 'checked',
            'ribbonlabel'   => 'Hot Deal',
            'newlabel'      => 'test',
            'sort'          => '',
            'showribbon'    => '',
            'ribbonlabel1'   => 'Best Deal',
            'ribbonlabel2'   => 'Low Rates',
            'ribbonlabel3'   => 'Reccomended',
            'ribbonlabel4'   => 'Ice Cream!',

            'showfees'      => '',
            'showterm'      => '',
            'nobuttons'     => '',
            'interest'      => 'amortisation'
        );
    }

?>